...
git:
  depth: 1
  
before_install: echo "running"

install: echo "running"

before_script: echo "running"

script: echo "running"

after_success: echo "running"

after_failure: echo "running"

before_deploy: echo "running"

# https://docs.travis-ci.com/user/deployment/script/
deploy:
  # deploy develop to the staging environment
  - provider: script
    script: echo staging
    on:
      branch: develop
  # deploy master to production
  - provider: script
    script: echo production
    on:
      branch: master

after_deploy: echo "running"

after_script: echo "running"
---
