...
git:
  depth: 1
  
before_install: echo "running"

install: echo "running"

before_script: echo "running"

script: echo "running"

after_success: echo "running"

after_failure: echo "running"

before_deploy: echo "running"

# https://docs.travis-ci.com/user/deployment/script/
deploy:
  provider: script
  script: echo deploy
  on:
    branch: master

after_deploy: echo "running"

after_script: echo "running"
